<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MotorcycleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotorcycleRepository extends EntityRepository {

    public function findAllActive() {
        return $this->getEntityManager()
                        ->createQuery(
                                "SELECT o FROM AppBundle:Motorcycle o ORDER BY o.price DESC"
                        )
                        ->getResult();
    }
}