<?php

namespace AppBundle\Repository;

/**
 * TypeMotorcycleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeMotorcycleRepository extends \Doctrine\ORM\EntityRepository
{
}
